version: '3.8'
services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    ports:
      - 5432:5432
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5173:5173
    networks:
      - transcendence
networks:
  transcendence: